[tools]
aws = "latest"
bat = 'latest'
delta = 'latest'
eza = 'latest'
go = "latest"
hyperfine = "latest"
jq = "latest"
mc = "latest"
mysql = "latest"
neovim = 'latest'
node = "23.7.0"
ripgrep = 'latest'
rust = "latest"
tmux = 'latest'
uv = "latest"
yarn = 'latest'
