[tools]
bat = 'latest'
delta = 'latest'
difftastic = { version = 'latest', exe = 'difft' }
eza = 'latest'
gh = "latest"
ghq = "latest"
go = "latest"
jq = "latest"
neovim = 'latest'
node = 'latest'
python = "latest"
ripgrep = 'latest'
tmux = '3.4'
yarn = 'latest'
