name: test
on:
  - push
jobs:
  test:
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v5
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
